### ISSUE TITLE
Can you please add an example with an API. I'm facing an error in example you provided.

### ISSUE THREAD

**Issue by sgvadodariya** [cloudb2/processus#14]
var processus = require('processus');

var wf = {
  "name": "Example Workflow",
  "description": "An example workflow using the API.",
  "tasks":{
    "task 1": {
      "description": "Demo task to execute echo command.",
      "blocking": true,
      "handler" : "../taskhandlers/execHandler",
      "parameters": {
        "cmd": "echo 'Congratulations you called a workflow using the API.'"
      }
    }
  }
};

processus.execute(wf, function(err, workflow){
  if(!err) {
    console.log(workflow.tasks['task 1'].parameters.stdout);
  } else {
    console.log(err);
  }
});

I'm getting below error.

D:\wamp64\www\Demos\processus>node test.js
TypeError: Cannot read property 'dataDirectory' of undefined
    at Object.saveInstance (D:\wamp64\www\Demos\processus\node_modules\processus\engine\persistence\file.js:273:24)
    at Object.saveInstance (D:\wamp64\www\Demos\processus\node_modules\processus\engine\persistence\store.js:118:35)
    at realExecute (D:\wamp64\www\Demos\processus\node_modules\processus\engine\processus.js:317:9)
    at D:\wamp64\www\Demos\processus\node_modules\processus\engine\processus.js:143:11
    at executePrePost (D:\wamp64\www\Demos\processus\node_modules\processus\engine\processus.js:193:5)
    at doPre (D:\wamp64\www\Demos\processus\node_modules\processus\engine\processus.js:172:3)
    at Object.execute (D:\wamp64\www\Demos\processus\node_modules\processus\engine\processus.js:141:5)
    at Object.execute (D:\wamp64\www\Demos\processus\node_modules\processus\engine\api.js:67:5)
    at Object.<anonymous> (D:\wamp64\www\Demos\processus\test.js:18:11)
    at Module._compile (module.js:571:32)

**Comment by jasoncb2** [comment]
Hi @sgvadodariya apologies for the delayed response. You need to initialise the store which should probably be done processus.js itself. Anyway, here's a work around
```
var processus = require('processus');
var store = require('processus/engine/persistence/store');
store.initStore(function(err){
  console.log(err);
});

var wf = {
  "name": "Example Workflow",
  "description": "An example workflow using the API.",
  "tasks":{
    "task 1": {
      "description": "Demo task to execute echo command.",
      "blocking": true,
      "handler" : "../taskhandlers/execHandler",
      "parameters": {
        "cmd": "echo 'Congratulations you called a workflow using the API.'"
      }
    }
  }
};

processus.execute(wf, function(err, workflow){
  if(!err) {
    console.log(workflow.tasks['task 1'].parameters.stdout);
  }
  else {
    console.log(err);
  }
});
```

which should result in the following:

```
info: ⧖ Starting task [task 1]
info: Congratulations you called a workflow using the API.
info: ✔ task task 1 completed successfully.
Congratulations you called a workflow using the API.

```

**Comment by jasoncb2** [comment]
For more info on the store and parameters, look at how the [cli.js](https://github.com/cloudb2/processus/blob/master/engine/cli.js) code uses processes to do the same.

**Comment by jasoncb2** [comment]
Updated readme to include store initialization in API example. Closing this accordingly.
