### ISSUE TITLE
Unable to integrate with express JS

### ISSUE THREAD

**Issue by shivasr** [cloudb2/processus#15]
When I initialize the web app and call 

var processus = require('processus');

var wf = {
  "name": "Example Workflow",
  "description": "An example workflow using the API.",
  "tasks":{
    "task 1": {
      "description": "Demo task to execute echo command.",
      "blocking": true,
      "handler" : "../taskhandlers/execHandler",
      "parameters": {
        "cmd": "echo 'Congratulations you called a workflow using the API.'"
      }
    }
  }
};

processus.execute(wf, function(err, workflow){
  if(!err) {
    console.log(workflow.tasks['task 1'].parameters.stdout);
  } else {
    console.log(err);
  }
});

It gives me below error stack:

TypeError: Cannot read property 'dataDirectory' of undefined
    at Object.saveInstance (C:\Users\ezmairs\Documents\projects\git\jobs\node_modules\processus\engine\persistence\file.js:273:25)
    at Object.saveInstance (C:\Users\ezmairs\Documents\projects\git\jobs\node_modules\processus\engine\persistence\store.js:118:35)
    at realExecute (C:\Users\ezmairs\Documents\projects\git\jobs\node_modules\processus\engine\processus.js:317:9)
    at C:\Users\ezmairs\Documents\projects\git\jobs\node_modules\processus\engine\processus.js:143:11
    at executePrePost (C:\Users\ezmairs\Documents\projects\git\jobs\node_modules\processus\engine\processus.js:193:5)
    at doPre (C:\Users\ezmairs\Documents\projects\git\jobs\node_modules\processus\engine\processus.js:172:3)
    at Object.execute (C:\Users\ezmairs\Documents\projects\git\jobs\node_modules\processus\engine\processus.js:141:5)
    at Object.execute (C:\Users\ezmairs\Documents\projects\git\jobs\node_modules\processus\engine\api.js:67:5)
    at Object.<anonymous> (C:\Users\ezmairs\Documents\projects\git\jobs\jobs.js:18:11)
    at Module._compile (module.js:660:30)

**Comment by jasoncb2** [comment]
Hi, @shivasr apologies for the delayed response. This is a known issue, you need to initalize the stor before making an API call. Here is an example:

```
var processus = require('processus');
var store = require('processus/engine/persistence/store');
store.initStore(function(err){
  console.log(err);
});

var wf = {
  "name": "Example Workflow",
  "description": "An example workflow using the API.",
  "tasks":{
    "task 1": {
      "description": "Demo task to execute echo command.",
      "blocking": true,
      "handler" : "../taskhandlers/execHandler",
      "parameters": {
        "cmd": "echo 'Congratulations you called a workflow using the API.'"
      }
    }
  }
};

processus.execute(wf, function(err, workflow){
  if(!err) {
    console.log(workflow.tasks['task 1'].parameters.stdout);
  }
  else {
    console.log(err);
  }
});
```

which should result in the following:

```
info: ⧖ Starting task [task 1]
info: Congratulations you called a workflow using the API.
info: ✔ task task 1 completed successfully.
Congratulations you called a workflow using the API.

```

**Comment by jasoncb2** [comment]
This is related to #14 - closing accordingly.

**Comment by shivasr** [comment]
Thanks!

I have already understood your code and applied fix myself and developed many more features.

I have written couple of handlers for ansible and couple of customisation.

Thanks 
Shiva
